Fix Windows build
ERROR: failed to solve: failed to compute cache key: mount callback failed on /tmp/containerd-mount1917080101: link /tmp/containerd-mount1917080101/Windows/INF/basicrender.inf /tmp/containerd-mount1917080101/Windows/System32/DriverStore/FileRepository/basicrender.inf_amd64_efdc64af60c69a6d/basicrender.inf: no such file or directory
Error: Process completed with exit code 1.

According to [1], we need to use ltsc2022 as a tag.

[1] https://github.com/microsoft/Windows-Containers/issues/493

Signed-off-by: Masashi Honma <masashi.honma@gmail.com>